name: "SaveIt"
description: "A new Flutter project with authentication using Laravel and MySQL."

# Evita que la app se publique accidentalmente en pub.dev
publish_to: 'none'

# Configuraci贸n de versi贸n de la app
version: 1.0.0+1

# Versi贸n del SDK de Dart requerida
environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependencias de la aplicaci贸n
dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter

  fl_chart: ^1.0.0


  #  Manejo de peticiones HTTP (Conexi贸n con el backend Laravel)
  http: ^1.4.0
  dio: ^5.4.0
  cherry_toast: ^1.1.0

  #  Guardar datos localmente (Almacenar tokens JWT y preferencias de usuario)
  shared_preferences: ^2.2.2

  #  Manejo de estados en la app (Opcional, pero recomendado)
  provider: ^6.0.5

  #  Almacenamiento seguro para tokens (Opcional, mejora seguridad)
  flutter_secure_storage: ^9.2.4

  #  conos estilo iOS
  cupertino_icons: ^1.0.6

# Dependencias solo necesarias para desarrollo y pruebas
dev_dependencies:
  flutter_test:
    sdk: flutter

  #  Buenas pr谩cticas y estilo de c贸digo
  flutter_lints: ^5.0.0

# Configuraci贸n espec铆fica para Flutter
flutter:
  uses-material-design: true

  # Puedes agregar assets (im谩genes, fuentes, etc.) aqu铆
  assets:
   #- assets/images/
   - assets/images/logo_login.png


         # Puedes agregar fuentes personalizadas aqu铆
  #fonts:
   # - family: Roboto
    #  fonts:
        #- asset: assets/fonts/Roboto-Regular.ttf
        #- asset: assets/fonts/Roboto-Bold.ttf
       #   weight: 700
